spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**
          - id: restaurant-service
            uri: lb://restaurant-service
            predicates:
              - Path=/api/v1/restaurants/**
          - id: rating-service
            uri: lb://rating-service
            predicates:
              - Path=/api/v1/ratings/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payments/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: menu-service
            uri: lb://menu-service
            predicates:
              - Path=/api/v1/menus/**
          - id: driver-service
            uri: lb://driver-service
            predicates:
              - Path=/api/v1/drivers/**
          - id: address-service
            uri: lb://address-service
            predicates:
              - Path=/api/v1/address/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8010